# Generated by Django 4.2.2 on 2023-07-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_prince',
            new_name='selling_price',
        ),
    ]
