# Generated by Django 4.2.2 on 2023-07-11 18:16

from django.db import migrations, models
import django.db.models.deletion
import nammashop.models


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0002_rename_selling_prince_product_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=nammashop.models.getFileName)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nammashop.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
