# Generated by Django 4.2.2 on 2023-07-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0004_product_delete_new_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
