# Generated by Django 4.2.2 on 2023-07-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0009_rename_washingmachine_category_electronic_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Electronic_Category',
        ),
    ]
