# Generated by Django 4.2.2 on 2023-07-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
    ]
