# Generated by Django 4.2.2 on 2023-07-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0013_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
    ]
