# Generated by Django 4.2.2 on 2023-07-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0016_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
