# Generated by Django 4.2.2 on 2023-07-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nammashop', '0017_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
